### ISSUE TITLE
Docker-compose sticks at "Building wheel for uvloop (setup.py): started"

### ISSUE THREAD

**Issue by crege2** [solero/wand#5] opened 2020-06-12 22:01 UTC
When I run `sudo docker-compose up` after setting up the .env file the install always gets stuck at `Building wheel for uvloop (setup.py): started` and then times out and fails.

**Comment by ketnipz** [comment] 2020-06-12 22:04
Please post the full output (or at least all relevant output) so we can determine the cause of this.

**Comment by crege2** [comment] 2020-06-12 22:06
This is the whole output that I get from the command `sudo docker-compose up`

`Building houdini_login
Step 1/8 : FROM python:3-alpine
 ---> 8ecf5a48c789
Step 2/8 : RUN apk add     openssl     build-base     openssl-dev     libffi-dev     redis     postgresql-client
 ---> Using cache
 ---> 7da6e41a17d9
Step 3/8 : WORKDIR /usr/src/houdini
 ---> Using cache
 ---> 08ee2fcd3858
Step 4/8 : ENV DOCKERIZE_VERSION v0.6.1
 ---> Using cache
 ---> fab9443375ce
Step 5/8 : RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz     && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz     && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
 ---> Using cache
 ---> 9046cba61eeb
Step 6/8 : COPY requirements.txt ./
 ---> Using cache
 ---> 46f3da6d5e05
Step 7/8 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 75636480397a
Collecting asyncio
  Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
Collecting aioredis
  Downloading aioredis-1.3.1-py3-none-any.whl (65 kB)
Collecting cacheout
  Downloading cacheout-0.11.2-py3-none-any.whl (17 kB)
Collecting gino
  Downloading gino-1.0.1-py3-none-any.whl (49 kB)
Collecting ujson
  Downloading ujson-3.0.0.tar.gz (7.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting bcrypt
  Downloading bcrypt-3.1.7.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting uvloop
  Downloading uvloop-0.14.0.tar.gz (2.0 MB)
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting hiredis
  Downloading hiredis-1.0.1.tar.gz (54 kB)
Collecting async-timeout
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting asyncpg<1.0,>=0.18
  Downloading asyncpg-0.20.1.tar.gz (734 kB)
Collecting SQLAlchemy<1.4,>=1.2.16
  Downloading SQLAlchemy-1.3.17.tar.gz (6.0 MB)
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cffi>=1.1
  Downloading cffi-1.14.0.tar.gz (463 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: ujson, bcrypt, uvloop, hiredis, asyncpg, SQLAlchemy, cffi
  Building wheel for ujson (PEP 517): started
  Building wheel for ujson (PEP 517): finished with status 'done'
  Created wheel for ujson: filename=ujson-3.0.0-cp38-cp38-linux_x86_64.whl size=43965 sha256=d78304f4318fa6ccd9db85b6afb4398f56aa1e1c40ee3caaea7d016ea09c6bc0
  Stored in directory: /tmp/pip-ephem-wheel-cache-3i9pwos9/wheels/6a/cd/7e/3e149f2d4971bdb0730722fa5121c3226c7340df5dabd89fba
  Building wheel for bcrypt (PEP 517): started
  Building wheel for bcrypt (PEP 517): finished with status 'done'
  Created wheel for bcrypt: filename=bcrypt-3.1.7-cp38-cp38-linux_x86_64.whl size=31688 sha256=fa71bebdc0933307a0810867669ae6d752ebf34b02cdcaae7dc1007f02813fb5
  Stored in directory: /tmp/pip-ephem-wheel-cache-3i9pwos9/wheels/08/dd/04/63fe9a4002c36105c358f90221e4882825a264edb9d8554163
  Building wheel for uvloop (setup.py): started

`

**Comment by GrizzyWasProgrammed** [comment] 2020-06-12 22:06
sudo apt install python3-uvloop

**Comment by ketnipz** [comment] 2020-06-12 22:07
This part of the build process can take some time, especially on less powerful machines.

Does this just suddenly stop and give you terminal control back, or is it just taking a long time...



> sudo apt install python3-uvloop

This command is useless, since he's setting up using Docker.

**Comment by crege2** [comment] 2020-06-12 22:09
Okay I will just let it run and hope that the process doesn't time out.

**Comment by ketnipz** [comment] 2020-06-12 22:11
I am not sure what you mean by the process times out?

This command should run until it has finished. Does it suddenly stop and give some error? Or are you just being impatient!

Also check you meet this spec:

CPU: 1vCore
RAM: > 2GB
DISK: > 30GB

**Comment by crege2** [comment] 2020-06-12 22:12
Usually my ssh tunnel breaks before the command can finish.

**Comment by GrizzyWasProgrammed** [comment] 2020-06-12 22:13
I had this problem as well and i went a closed putty and reopened my putty and ran "screen -S username sudo docker-compose up" and when it says server's online pressing ctrl - a+d worked but this might not work for you.

**Comment by ketnipz** [comment] 2020-06-12 22:15
Yes, one solution if you have a intermittent SSH connection would be to use screen to run the install process. This way if you lose your SSH session it will keep running. 

Be careful though, once you detach from the screen session it is still running! Avoid running the command twice at once.

**Comment by crege2** [comment] 2020-06-12 22:17
> Be careful though, once you detach from the screen session it is still running! Avoid running the command twice at once.

Is there a way that I can see the progression of the command before the container is finished building?

**Comment by ketnipz** [comment] 2020-06-12 22:19
> Is there a way that I can see the progression of the command before the container is finished building?

Yes, say I ran the command

`screen sudo docker-compose up`

And then detached/got disconnected from SSH session.

I can run `screen -ls` to see all screen sessions and then rejoin with:

`screen -r session_id_from_screen_ls`

**Comment by ketnipz** [comment] 2020-06-12 22:23
Closing this issue because nothing needs to be fixed.

Further questions please ask in the [discord](https://solero.me/discord).

**Closed by ketnipz** 2020-06-12 22:23 UTC
